### ISSUE TITLE
getting IsaDirectory Error no.21 while running this container

### ISSUE THREAD

**Issue by chetanpjain** [logzio/logzio-pubsub#15]
error logs is : 
```
Traceback (most recent call last):
  File "filebeat-yml-script.py", line 50, in <module>
    _add_all_topics()
  File "filebeat-yml-script.py", line 14, in _add_all_topics
    with open("pubsub-input.yml", "r") as input_yml:
IsADirectoryError: [Errno 21] Is a directory: 'pubsub-input.yml'
```
pubsub-input.yml file is present and is a valid yml file, not sure why running into this error.

**Comment by chetanpjain** [comment]
got to run it with configMap in k8s, closing it.
